name: Release to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MCPSharp/MCPSharp.csproj
      
    - name: Build
      run: dotnet build MCPSharp/MCPSharp.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test MCPSharp/MCPSharp.csproj --no-build --configuration Release --verbosity normal
      
    - name: Pack
      run: dotnet pack MCPSharp/MCPSharp.csproj --no-build --configuration Release -p:PackageVersion=${{ github.event.inputs.version }} --output nupkgs
      
    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
